WIP: solved core dependency folder-encrypt package missing; new error instead
An unhandled rejection has occurred inside Forge:
Error: ENOENT: no such file or directory, stat '/private/var/folders/8d/s8q4lntj4k1gsfdp66lj1h1m0000gn/T/electron-packager/tmp-lpvmWy/Electron.app/Contents/Resources/app/node_modules/core'